In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,MissingIndicator

In [7]:
df=pd.read_csv("C:/Users/sanke/Downloads/train (1).csv",usecols=['Age','Fare','Survived'])

In [9]:
df.head()

,Survived,Age,Fare
0,0,22.0,7.2500
1,1,38.0,71.2833
2,1,26.0,7.9250
3,1,35.0,53.1000
4,0,35.0,8.0500


In [11]:
x=df.drop(columns='Survived')
y=df['Survived']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=15)

In [15]:
x_train.head()

,Age,Fare
530,2.0,26.0000
124,54.0,77.2875
56,21.0,10.5000
424,18.0,20.2125
664,20.0,7.9250


# Without using Missing indictor

In [20]:
si=SimpleImputer()
x_train_trf=si.fit_transform(x_train)
x_test_trf=si.transform(x_test)

In [22]:
x_train_trf

array([[ 2.    , 26.    ],
       [54.    , 77.2875],
       [21.    , 10.5   ],
       ...,
       [48.    , 76.7292],
       [18.    , 11.5   ],
       [65.    , 26.55  ]])

In [26]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(x_train_trf,y_train)

y_pred = clf.predict(x_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.664804469273743

# Using MissingIndicator

In [29]:
mi = MissingIndicator()
mi.fit(x_train)

MissingIndicator()

In [33]:
mi.features_

array([0], dtype=int64)

In [35]:
x_train_missing=mi.transform(x_train)

In [37]:
x_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [

In [39]:
x_test_missing=mi.transform(x_test)

In [41]:
x_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [

In [43]:
x_train['Age_NA']=x_train_missing

In [47]:
x_train

,Age,Fare,Age_NA
530,2.0,26.0000,False
124,54.0,77.2875,False
56,21.0,10.5000,False
424,18.0,20.2125,False
664,20.0,7.9250,False
...,...,...,...
384,NaN,7.8958,True
887,19.0,30.0000,False
645,48.0,76.7292,False
757,18.0,11.5000,False


In [49]:
x_test['Age_NA']=x_test_missing

In [51]:
x_test

,Age,Fare,Age_NA
310,24.0,83.1583,False
635,28.0,13.0000,False
44,19.0,7.8792,False
698,49.0,110.8833,False
750,4.0,23.0000,False
...,...,...,...
20,35.0,26.0000,False
771,48.0,7.8542,False
865,42.0,13.0000,False
685,25.0,41.5792,False


In [53]:
si = SimpleImputer()

X_train_trf2 = si.fit_transform(x_train)
X_test_trf2 = si.transform(x_test)

In [59]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)

y_pred2 = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.659217877094972

# Using Simple Imputer's Class

In [62]:
si=SimpleImputer(add_indicator=True)

In [64]:
X_train2=si.fit_transform(x_train)

In [72]:
X_test2=si.transform(x_test)

In [74]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train2,y_train)
y_pred=clf.predict(X_test2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.659217877094972